
# If MySQL is disabled, we will use SQLite
mysql:
  enabled: false
  host: 'localhost'
  database: 'database'
  username: 'username'
  password: 'password'
  port: 3306
  useSSL: false

# Should we auto-save player data in an interval?
# The interval is in seconds
# Required restart If you want to change
autoSave:
  enabled: true
  interval: 300
  sendMessage: true

# Should we notified you when there's an update?
notifyUpdate: true

# How many mobcoins should player start with
starting-balance: 0

# This is the command aliases
aliases:
  - "mc"
  - "mobcoin"
  - "aliascoin"

# Configuration Information:
#   (physicalMobCoin) should we use physical mobcoins instead virtual mobcoins?
#   (disableMobCoinFromSpawner) should we prevent mob that spawn from spawner to drop mobcoins?
mobcoins:
  physicalMobCoin: false
  disableMobCoinFromSpawner: true
  enableMobCoinsReceiveMessage: true

# Configuration Information:
#   (shopBehaviour) Basically tells the plugin what menu should opened up upon executing shop command
#   (shopBehaviour) Available behaviour: MAIN_MENU, ROTATING_SHOP, CATEGORY_SHOP
#   (closeAfterPurchase) Should we close the inventory after purchase?
#   (confirmationMenu) Should we use confirmation menu when purchasing item?
#   (autoUpdate)
#     (enabled) should we always update inventory items info?
#     (updateEvery) how often should we update the items (in ticks, 20 ticks = 1 second)?
shops:
  shopBehaviour: MAIN_MENU
  closeAfterPurchase: false
  confirmationMenu: true
  autoUpdate:
    enabled: true
    updateEvery: 20

# If you enabled this mode, player will receive notification
# every x amount of seconds on how much that they receive
# mobcoins in that time.
# Configuration Information:
#   (announceEvery) the time is in seconds, 300 seconds = 5 minute.
#   (receiveAfterMessage) should player receive mobcoins after the notification?
#
salaryMode:
  enabled: true
  announceEvery: 300
  receiveAfterMessage: false
  messages:
    - ''
    - '&6&l[!] Mob &e&lCoins &7(Earning Summary)'
    - '&fYou have earned &6{amount} coins &fin the past 5 minutes!'
    - ''

# List of all placeholders that are being used
# Information:
# placeholders:
#   (unlimitedStock) Will be used when shop item doesn't use stock system
#   (outOfStock) Will be used when shop items is out of stock
#   (mobCoinsTop) All placeholders for mobcoins top leaderboard
#     (nameIfEmpty) Will be used If there is no player on that position
#     (balanceIfEmpty) Will be used If there is no player on that position
#     (uuidIfEmpty) Will be used If there is no player on that position
#----------------------------------------------------------------------
placeholders:
  unlimitedStock: "&aUnlimited"
  outOfStock: "&c&lOUT OF STOCK"
  mobCoinsTop:
    nameIfEmpty: "&7None"
    balanceIfEmpty: "0"
    uuidIfEmpty: "none"

# What world should we disable player from receiving mobcoin?
disabledWorlds:
  - 'exampleWorld'
  - 'theonly_world'

# MobCoins items that will be used for physical mobcoin.
mobcoinsItem:
  material: SUNFLOWER
  name: "&e&lMobcoins &7(Right Click)"
  glow: false
  lore:
    - '&7You can use mobcoins to purchase'
    - '&7items on /mobcoins shop!'
    - ''
    - '&6{amount} coins &7are stored in this item!'
    - ''
    - '&6Right click to redeem!'

# Configuration Information
#   (enabled) should we enabled this sound?
#   (name) the name of the sound (https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html)
#   (volume) the volume of the sound
#   (pitch) the pitch of the sound
sounds:
  onCoinsRedeem:
    enabled: true
    name: ENTITY_PLAYER_LEVELUP
    volume: 1.0
    pitch: 1.0
  onCoinsReceived:
    enabled: true
    name: BLOCK_NOTE_BLOCK_PLING
    volume: 1.0
    pitch: 1.0

# Format Information
# titleKey:
#   (enabled) should we send this title to player?
#   (title) the title on the titlebar
#   (subtitle) the subtitle on the titlebar
#   (fadeIn) fade in animation, time in ticks (20 ticks = 1 second)
#   (stay) how long should the title stay, time in ticks (20 ticks = 1 second)
#   (fadeOut) fade out animation, time in ticks (20 ticks = 1 second)
titles:
  onCoinsReceived:
    enabled: true
    title: "&e&l+{amount} MobCoins"
    subTitle: "&fYou just received {amount} coins"
    fadeIn: 20
    stay: 40
    fadeOut: 20

actionBar:
  onCoinsReceived:
    enabled: true
    message: "&a+{amount} MobCoins"

messages:
  prefix: "&e[MobCoins]"
  noPermission: "{prefix} &cYou don't have enough permission!"
  reload: "{prefix} &aYou have reloaded the configuration &7(took {ms}ms)"
  balance: "{prefix} &fYour coins: &e{coins}"
  balanceOthers: "{prefix} &f{player}'s coins: &e{coins}"
  playerNotExists: "{prefix} &cThat player is not online!"
  notInt: "{prefix} &cThe amount argument is not a number!"
  addCoins: "{prefix} &aYou have given &e{amount} &a{type} coins to &e{player}"
  addCoinsOthers: "{prefix} &aYou have received &e{amount} &a{type} coins."
  invalidType: "{prefix} &cInvalid types! &7(physical, virtual)"
  removeCoins: "{prefix} &aYou have removed &e{amount} &acoins from &e{player}"
  removeCoinsOthers: "{prefix} &e{amount} &acoins has been removed from your account!"
  setCoins: "{prefix} &aYou have set &e{player} &acoins to &e{amount}"
  setCoinsOthers: "{prefix} &aYour coins has been set to &e{amount}"
  notEnoughCoins: "{prefix} &cYou don't have enough coins!"
  selfPay: "{prefix} &cYou can not give yourself coins!"
  pay: "{prefix} &aYou have given &e{amount} &acoins to &e{player}"
  payOthers: "{prefix} &aYou have received &e{amount} &acoins from &e{player}"
  redeem: "{prefix} &aYou have redeemed &e{amount} &acoins."
  coinsReceived: "{prefix} &aYou have received &e{amount} &acoins."
  itemOutOfStock: "{prefix} &cItem is out of stock!"
  purchaseLimitReached: "{prefix} &cYou can not purchase this item anymore!"
  minimumAmount: "{prefix} &cThe minimum amount is 1"
  inventoryFull: "{prefix} &cYour inventory is full, Please make some space!"
  withdraw: "{prefix} &aYou have withdrawed &6{amount} &acoins."
  categoryNotExists: "{prefix} &cCategory '{category}' is doesn't exist!"
  topLeaderboard:
    - "&6--------------------------------------"
    - "  &7Mobcoins Leaderboard"
    - ""
    - "   &6#1. &7%mobcoins_top_name_1% - &6%mobcoins_top_balance_formatted_1% coins"
    - "   &6#2. &7%mobcoins_top_name_2% - &6%mobcoins_top_balance_formatted_2% coins"
    - "   &6#3. &7%mobcoins_top_name_3% - &6%mobcoins_top_balance_formatted_3% coins"
    - "   &6#4. &7%mobcoins_top_name_4% - &6%mobcoins_top_balance_formatted_4% coins"
    - "   &6#5. &7%mobcoins_top_name_5% - &6%mobcoins_top_balance_formatted_5% coins"
    - "   &6#6. &7%mobcoins_top_name_6% - &6%mobcoins_top_balance_formatted_6% coins"
    - "   &6#7. &7%mobcoins_top_name_7% - &6%mobcoins_top_balance_formatted_7% coins"
    - "   &6#8. &7%mobcoins_top_name_8% - &6%mobcoins_top_balance_formatted_8% coins"
    - "   &6#9. &7%mobcoins_top_name_9% - &6%mobcoins_top_balance_formatted_9% coins"
    - "   &6#10. &7%mobcoins_top_name_10% - &6%mobcoins_top_balance_formatted_10% coins"
    - ""
    - "&6--------------------------------------"
  help:
    - "Current Help"
    - "/mobcoins help"
    - "/mobcoins balance"
  helpAdmin:
    - "Admin Help"
    - "/mobcoins help"
    - "/mobcoins balance"